### ISSUE TITLE
How to add a title in formly within templateOptions 

### ISSUE THREAD

**Issue by AmarjyotiSAG** [ngx-formly/ngx-formly#3377]
On hover of label, I want to display title of the label.
screenshort is attached:-
according to schreenshort I wanted on hover of "General" I want to display title.
![Capture formly](https://user-images.githubusercontent.com/107403150/178252387-f7d25a6d-0684-472a-92ef-bc15b52b1974.PNG)

**Comment by aitboudad** [comment]
see https://formly.dev/examples/other/nested-formly-forms

**Comment by aitboudad** [comment]
> according to schreenshort I wanted on hover of "General" I want to display title.

if you follow the above example, you can handle the hove part inside `PanelWrapperComponent` or simply with css selector:

```scss
formly-wrapper-panel .card {
  .card-body { display: none; }
  &:hover {
    .card-body { display: block; }
  }
}
```
