### ISSUE TITLE
Change of formly-field style  

### ISSUE THREAD

**Issue by dhulipala** [ngx-formly/ngx-formly#3772]
Hi,

I have a scenario where based on change of one field another field is hidden inside a form.
The styling of the hidden field is default to 'display:none'; due to which other columns in that row are moving. Is there a way to change the style to 'visibility:hidden' instead.

thanks,
sd

**Comment by aitboudad** [comment]
You can use the following style:

```scss
formly-field:empty {
  display: unset !important;
  visibility: hidden;
}
```

To apply it for a specific field only,  pass a custom `className`:

```ts
{
  key: 'name',
  className: 'custom-class',
  ...
}
```
